Fixed Ventoy drive copy typo
ChrisTitusTech/winutil pull request #1727
Opened 2024-03-26 12:23 UTC by CodingWonders

This PR fixes a typo in the Ventoy drive copy function spotted by @JoKopii, on PR #1384 (!)

2024-03-26 15:06 UTC, NewCodingAI approved these changes

2024-03-28 12:09 UTC, og-mrk requested changes
The changes in this commit looks fine, but the tabs & spaces are mixed, fix in a new commit, or change it and force-push the same commit changes but with the tabs/spaces issue resolved.

Overall good commits @CodingWonders, _and IK what I've previously stated is somewhat nitpicking_, but it's better to point these stuff out if, for example, you haven't noticed it while writing these changes.

2024-03-28 12:14 UTC, CodingWonders commented
> The changes in this commit looks fine, but the tabs & spaces are mixed, fix in a new commit, or change it and force-push the same commit changes but with the tabs/spaces issue resolved.
> 
> Overall good commits @CodingWonders, _and IK what I've previously stated is somewhat nitpicking_, but it's better to point these stuff out if, for example, you haven't noticed it while writing these changes.

The PS ISE causes the indentation issue - it never gets it right, and I can't just use VSCode because then the compilation script fails on me (stating that `winutil.ps1` is in use).

At least PowerShell is not like Python, where indentation matters

2024-03-28 12:26 UTC, og-mrk commented
> > The changes in this commit looks fine, but the tabs & spaces are mixed, fix in a new commit, or change it and force-push the same commit changes but with the tabs/spaces issue resolved.
> > Overall good commits @CodingWonders, _and IK what I've previously stated is somewhat nitpicking_, but it's better to point these stuff out if, for example, you haven't noticed it while writing these changes.
> 
> The PS ISE causes the indentation issue - it never gets it right, and I can't just use VSCode because then the compilation script fails on me (stating that `winutil.ps1` is in use).
> 
> At least PowerShell is not like Python, where indentation matters

Interesting problem you got there... well, good thing PowerShell doesn't depend on Indentation for scoping. Hope you find a solution for it.

2024-03-28 15:48 UTC, ChrisTitusTech approved these changes

2024-03-28 15:50 UTC, merged