Main window handle
ChrisTitusTech/winutil pull request #1941
Opened 2024-05-06 03:42 UTC by BKlaasWerkman

Condition is comparing $proc.Id with [System.IntPtr]::Zero. The Id property is an integer, representing the process ID, and it's not directly related to window handles. Instead, you should compare the MainWindowHandle property against [System.IntPtr]::Zero

2024-05-07 09:12 UTC, og-mrk requested changes
@BKlaasWerkman
If your proposed changes is only concerned with `main.ps1` File under `scripts` folder, then Why are you Submitting Change(s) made in `applications.json` File as well?

Either you cut this change from this PR, and make a New PR for it, Or update This PR's Title & Description to be more accurate/descriptive of your Changes.

**EDIT**: Noticed that you've made a separate PR for adding Microsoft Office App Entry to `applications.json` File. (here's [a link](https://github.com/ChrisTitusTech/winutil/pull/1946) to it) Now the best course of action is to not have this App Addition, by simply removing the commit titled `Add Microsoft Office apps`.

2024-05-07 13:27 UTC, BKlaasWerkman commented
@og-mrk Thanks for this. I've now removed the commits.

2024-05-07 14:42 UTC, og-mrk approved these changes
Looks good to me. Thanks for your contribution 😄

Some references:
> Process.MainWindowHandle: https://learn.microsoft.com/en-us/dotnet/api/system.diagnostics.process.mainwindowhandle?view=net-8.0
> IntPtr Example showcasing similar usecase of `IntPtr.Zero` but in C# (see the Second Example): https://learn.microsoft.com/en-us/dotnet/api/system.intptr.zero?view=net-8.0#remarks

2024-05-11 20:52 UTC, ChrisTitusTech approved these changes

2024-05-11 20:52 UTC, merged