Hyperlinks to about section
ChrisTitusTech/winutil pull request #2080
Opened 2024-06-12 17:06 UTC by MyDrift-user

- Added hyperlinks for infos in the Author About Box
- Renamed Github link name because it is linked now
- added hover effect
- added link to release page of release

2024-06-20 18:59 UTC, ChrisTitusTech approved these changes

2024-06-20 19:06 UTC, ChrisTitusTech requested changes
![image](https://github.com/ChrisTitusTech/winutil/assets/7896101/106d60fd-50ec-42aa-aa3a-e135cc18a274)
Running into hyperlink error when click on link after compiling.

2024-06-20 20:01 UTC, MyDrift-user commented
I wasn't able to recreate the problem myself but I now changed the way that it opens the link.
- It now uses `Start-Process` instead of `[System.Diagnostics.Process]::Start`

Could someone with that problem please try it out and give Feedback? Thanks :)

2024-06-25 18:54 UTC, ChrisTitusTech commented
Perfect runs great now!

2024-06-25 18:54 UTC, merged