Run as admin if not already
ChrisTitusTech/winutil pull request #2531
Opened 2024-08-07 12:07 UTC by psyirius

## Title
Run as admin if not already

## Type of Change
- [x] New feature

## Description
Run the script as admin if detected running as a non-admin

## Testing
[Detail the testing you have performed to ensure that these changes function as intended. Include information about any added tests.]

## Impact
Will prevent the hassle of running the terminal or pwsh as admin before-hand

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-08-07 12:19 UTC, MyDrift-user commented
this was done something like that before, but it got changed due to antiviruses flagging it more often as a virus.
Idk how it behaves now that we have code signing..

2024-08-07 13:25 UTC, psyirius commented
I think it will work good if got codesignature

2024-08-07 14:17 UTC, MyDrift-user requested changes
Hey @psyirius 
It looks good, added the option to use Powershell 7 if possible in the review

2024-08-07 14:17 UTC, MyDrift-user commented on scripts/start.ps1
> +# RunAs admin if not already
how about doing it like following example?
I've reworked layouting a bit to match the rest of the utility and made it use ps7 if possible.

```
# Check if the current user is an administrator
if (-not ([Security.Principal.WindowsPrincipal]([Security.Principal.WindowsIdentity]::GetCurrent())).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
    
    # Determine which PowerShell executable to use
    if (Get-Command "pwsh" -ErrorAction SilentlyContinue) {
        $shell = "pwsh.exe"
    } else {
        $shell = "powershell.exe"
    }

    # Elevate the script and exit the current non-elevated script
    $PwshArgList = @(
        "-NoLogo",                                  # Don't print PowerShell header in CLI
        "-NoProfile",                               # Don't load PowerShell profile
        "-File", $MyInvocation.MyCommand.Source,    # Script path
        $args | ForEach-Object { $_ }               # Script arguments
    ) | ForEach-Object { "`"$_`"" }

    Start-Process -FilePath $shell -ArgumentList $PwshArgList -Verb RunAs
    exit
}
```

2024-08-07 14:54 UTC, MyDrift-user approved these changes
nice, thanks @psyirius

2024-08-07 22:08 UTC, psyirius commented
Looks like there's an issue.

DONT MERGE!

2024-08-07 22:13 UTC, psyirius commented
> Looks like there's an issue.
> 
> Crashing on already admin powershell.

Works now..
Weird! 

Looks like this caused by some weird edge case occurs around the UI spawning area!

2024-08-08 14:28 UTC, ChrisTitusTech commented
I think we can add this back in as well. Sometime AV still flags it which makes me think the elevation doesn't even matter. I'm starting to become skeptical if AV's actually do any scanning or code analyzation of that sort.

2024-08-08 20:54 UTC, MyDrift-user commented
Hey @psyirius 

Just got an Idea of #2543, how about readding the "needs to start as admin" notification if the user presses no when it asks to run the shell as admin? idk how easy it is to track that down tho..

2024-08-08 21:15 UTC, psyirius commented
Hmm.. We that'll be good.

Maybe process exit code?

2024-08-08 21:57 UTC, psyirius commented
Also gotta think about the iex execution situation

2024-08-08 22:16 UTC, MyDrift-user approved these changes
looks good and works, thanks @psyirius

2024-08-08 23:10 UTC, psyirius commented
> looks good and works, thanks @psyirius

Have you checked the InvokeScript Scenario?

I don't think using `iex` populates the `$MyInvocation.MyCommand.Source` with anything!

2024-08-08 23:27 UTC, MyDrift-user commented
Did not, but will.
Before it wasn't this variable but just an irm christitus.com/win | iex.
Idk how good that now would be that we habe a dev branch..

2024-08-09 15:04 UTC, psyirius commented
Either we use a stub or get dirty with process tokens and privileges!

2024-08-09 16:10 UTC, psyirius commented
I'm working on a stub that might help.

2024-08-10 12:38 UTC, MyDrift-user requested changes
Well everything works and I generally approve exept for the `$MyInvocation.MyCommand.Source`, before there was just another call to the github url, but because we have a dev branch now I would rather try fixing this. I also tried some stuff that came to my mind but nothing worked yet xD

2024-08-10 20:03 UTC, psyirius commented
IG a stub which then downloads and executes the main script is the painless way!

2024-08-13 18:51 UTC, psyirius commented
@ChrisTitusTech DONT MERGE THIS NOW!

BREAKS THE ONE-LINER LAUNCHER!!!

2024-08-13 18:54 UTC, ChrisTitusTech approved these changes

2024-08-13 18:55 UTC, psyirius commented
@ChrisTitusTech DONT DO IT!

2024-08-13 18:56 UTC, psyirius commented
READ THE ABOVE COMMENTS FOR MORE

2024-08-13 18:57 UTC, MyDrift-user commented
$myinvocation is the issue

2024-08-13 18:58 UTC, psyirius commented
😮‍💨

2024-08-14 20:01 UTC, ChrisTitusTech commented
Sooo I got bored and figured I would do a rewrite to fix the problems I see. 

I wanted a simple approach, but also have it use Windows terminal as it just looks a LOT better. I put in logic for wt, pwsh, and powershell depending on the system. 

Check out #2565

2024-08-16 05:15 UTC, ChrisTitusTech commented
> @ChrisTitusTech @MyDrift-user Is dropping the script to the disk a good idea?
> 
> Kanda test the behavior of it with AVs since we currently running fileless and some AVs miss it!

I'm indifferent about that. Dropping it to $env.temp wouldn't be a big deal. Its also rather small so downloading twice isn't a problem imo.

2024-08-16 05:27 UTC, MyDrift-user commented
> I'm indifferent about that. Dropping it to $env.temp wouldn't be a big deal. Its also rather small so downloading twice isn't a problem imo. 

The "big" difference zo last time is that we now have a dev brach, it would be cool if the functionality would support both release types.

2024-08-20 22:42 UTC, psyirius commented
@ChrisTitusTech @MyDrift-user Read the PR description before doing anything.

2024-08-20 23:04 UTC, psyirius commented
We can merge the windev script to this new launcher script as well. Lmk if that sounds good!

2024-08-21 00:41 UTC, Real-MullaC commented
Hello, Chris has done this in a PR #2565 what is a much better way of doing it. As it does not require adding, changing or removing of any URL's that people are used to.

2024-08-21 09:11 UTC, psyirius commented
> Hello, Chris has done this in a PR #2565 what is a much better way of doing it. As it does not require adding, changing or removing of any URL's that people are used to.

Read the above comment by @MyDrift-user

2024-08-21 09:49 UTC, Real-MullaC commented
@MyDrift-user and @psyirius Chris's PR will work fine. As it gets the latest pre release what has the winutil.ps1 file in it. What then runs on the system as the pre release. So Chris's PR will work fine for this.

2024-08-21 09:55 UTC, psyirius commented
> @MyDrift-user and @psyirius Chris's PR will work fine. As it gets the latest pre release what has the winutil.ps1 file in it. What then runs on the system as the pre release. So Chris's PR will work fine for this.

You're not getting the point here IG.
Have you checked https://github.com/ChrisTitusTech/winutil/pull/2565 from as windev and manual build (dev)

2024-08-21 10:49 UTC, MyDrift-user commented
I think u both kind of don't get it (not trying to be mean here)

2024-08-21 11:01 UTC, psyirius commented
> I think u both kind of don't get it (not trying to be mean here)

So, what are you suggesting?

2024-08-28 16:53 UTC, closed without merging