Provide a Toggle Option to Choose the Download Engine (Auto, Winget, Chocolatey)
ChrisTitusTech/winutil pull request #2596
Opened 2024-08-20 21:48 UTC by Marterich

## Type of Change
- [x] New feature
- [ ] Documentation update

## Description
In the past I've encountered the question "Why is Winget forced?" or "Why don't we have the Option to use Chocolatey instead because winget is to big/slow/broken"

This PR tries to implement a Toggle Option to Choose if 
- Winutil should automatically determine the best Download/Update Manager for the Usecase (Auto)
- Chocolatey should only be used (And all Packages that don't support it will be hidden)
- Winget should only be used (And all Packages that don't support it will be hidden)

![image](https://github.com/user-attachments/assets/5a6d0886-7390-4aba-95f0-0a1dde0cc606)

## Testing
Work In Progress

## Impact
[Discuss the impact of your changes on the project. This might include effects on performance, new dependencies, or changes in behavior.]

## Issue related to PR
[What issue/discussion is related to this PR (if any)]
- Resolves #

## Additional Information
[Any additional information that reviewers should be aware of.]

## Checklist
- [ ] My code adheres to the coding and style guidelines of the project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no errors/warnings/merge conflicts.

2024-08-20 22:19 UTC, ruxunderscore commented
Maybe, instead, we do a "Prefer Chocolatey" toggle instead, so that it's clear that Chocolatey will be handled first, unless there isn't a package in the choco repo. That was you can have the best of both worlds when it comes to Auto and Chocolatey only.

2024-08-20 22:24 UTC, Marterich commented
> Maybe, instead, we do a "Prefer Chocolatey" toggle instead, so that it's clear that Chocolatey will be handled first, unless there isn't a package in the choco repo. That was you can have the best of both worlds when it comes to Auto and Chocolatey only.

Interesting idea, will look into that tomorrow 
:) 

As a nice side factor this could simplify the implementation quite a bit

2024-08-29 01:09 UTC, ChrisTitusTech approved these changes
Looks awesome. I'm going to save this one for the Livestream as I want to checkout the branch and push it through some tests.

2024-08-29 05:38 UTC, MyDrift-user approved these changes

2024-09-10 18:01 UTC, Real-MullaC requested changes

2024-09-10 18:01 UTC, Real-MullaC commented on docs/dev/tweaks/Essential-Tweaks/Powershell7.md
Dont change this part of the file.

2024-09-10 18:02 UTC, merged