Patch 1
ChrisTitusTech/winutil pull request #2893
Opened 2024-10-09 13:09 UTC by cde2496

Add a few applications to the list.

## Type of Change
- [ ] New feature
- [ ] Bug fix
- [ ] Documentation update
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement
- [x] New Configuration

## Description
Added the following applications the the list:
- Directory Opus
- Java Runtime (JRE) 8
- MKVToolNix
- Media Player Classic - BE
- StartAllBack
- SyncBackFree
- Volume 2 Portable
- W10Privacy
- GameSave Manager

## Testing
Tested the installation on a dedicated VM.

## Impact
Just new applications to install.

## Issue related to PR
- None

## Additional Information
Most application are free to use.

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-10-09 17:13 UTC, Cryostrixx commented
Hello, @cde2496! Just a heads up new applications currently aren't being accepted into WinUtil so this PR won't be merged.

2024-10-10 20:24 UTC, ruxunderscore commented
Won't be merged. We are holding off on new applications for the time being, until the Applications UI overhaul is completed and merged. Also keep in mind, we tend to only accept programs that are FOSS, and always double check the fields for accuracy.

2024-10-11 08:29 UTC, Real-MullaC requested changes

2024-10-11 08:29 UTC, Real-MullaC commented on config/applications.json
> +        "winget": "na"
Please remove these and close your PR. As we are not adding any apps at the moment.

2024-10-30 16:59 UTC, closed without merging