KnownIssues: reformat, reorganize, clean up
ChrisTitusTech/winutil pull request #2899
Opened 2024-10-09 17:36 UTC by sevmonster

## Type of Change
- [ ] New feature
- [ ] Bug fix
- [x] Documentation update
- [ ] Refactoring
- [ ] Hotfix
- [ ] Security patch
- [ ] UI/UX improvement

## Description
Saw this page rendered on the site and it didn't look good; the tabs were what killed me but I also did some other work.

As in the commit message:
- fix bad tabulation in rendered markdown. GFM is very forgiving with tabs, but most implementations require four spaces per level.
- fix headers and header depth (H3 should not be the toplevel...)
- convert some list items to headers
- fix some grammar and reword some parts
- reorganize some list elements and sections
- unify use of key shortcut presentation (`Win`+`X`)
- convert some quoted words to italics
- don't include punctuation in emphasized/quoted technical words
- better explain some of the troubleshooting steps
- add key takeaways to battery health section
- other general proofreading

## Testing
N/A

## Impact
Headers will change, making old links not scroll to old anchors.

## Checklist
- [x] My code adheres to the coding and style guidelines of the project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no errors/warnings/merge conflicts.

2024-10-10 20:06 UTC, ruxunderscore commented
With my initial look, this is great, but I'll take another look with rendering in a bit. I always enjoy good formatting.

2024-10-11 08:32 UTC, Real-MullaC requested changes

2024-10-11 08:32 UTC, Real-MullaC commented on docs/KnownIssues.md
> -* If the problem persists after trying these steps, additional troubleshooting is required. Consider seeking assistance from Microsoft support or community forums for more specific guidance based on
This should be kept.

2024-10-20 19:54 UTC, ruxunderscore requested changes

2024-10-20 19:54 UTC, ruxunderscore commented on docs/KnownIssues.md
> +### Error `0x80041031`
Replace this with `### MicroWin: Error 0x80041031`

2024-11-07 18:05 UTC, ChrisTitusTech approved these changes

2024-11-07 18:06 UTC, merged